language: cpp

compiler:
  - gcc
  - clang

env:
  - VARIANT=debug
  - VARIANT=release

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then sudo apt-get update -qq; fi
  - echo -e 'import boost ;\nboost.use-project ;\n using gcc ;\n using clang ;' > ~/user-config.jam
  - cat ~/user-config.jam
  - wget https://github.com/boostorg/build/raw/develop/src/contrib/boost.jam -O ~/boost.jam

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then sudo apt-get install -qq libboost-all-dev; fi

# It just so happens that ${CC} corresponds to the BJam toolkit name.
script: bjam test ${CC} ${VARIANT}
